char* phrases[32] = {
    "Coding is like magic!",
    "Bananas are just yellow pickles.",
    "Penguins wear tuxedos every day.",
    "If cows could type, they'd write Moo++.",
    "I wish I could CTRL+Z in real life.",
    "Why don't scientists trust atoms? Because they make up everything!",
    "I put my phone in airplane mode, but it didn't fly!",
    "I speak fluent sarcasm.",
    "Don't trust stairs; they're always up to something.",
    "I'm on a seafood diet. I see food, and I eat it.",
    "I told my computer I needed a break, and now it won't stop sending me vacation ads.",
    "Why don't skeletons fight each other? They don't have the guts!",
    "I used to be a baker because I kneaded dough.",
    "My bed is a magical place where I suddenly remember everything I forgot to do.",
    "I told my computer a joke, but it didn't get it. Now I have a laughing laptop.",
    "I don't need a hairstylist; my pillow gives me a new hairstyle every morning.",
    "If you're ever feeling lonely, just remember there are billions of microscopic organisms living on you.",
    "Why did the programmer quit his job? He didn't get arrays!",
    "I can't believe I got fired from the calendar factory. All I did was take a day off!",
    "I told my coffee it was dark and bitter, just like my soul.",
    "Why did the scarecrow become a successful motivational speaker? Because he was outstanding in his field!",
    "My plants are dead. I'm not a plant killer; I'm just bad at gardening.",
    "I asked the librarian if the library had any books on paranoia. She whispered, 'They're right behind you.'",
    "I'm reading a book on anti-gravity. It's impossible to put down!",
    "Why don't scientists trust atoms? Because they make up everything!",
    "I'm writing a book on procrastination. I'll finish it someday.",
    "I told my wife she was drawing her eyebrows too high. She looked surprised.",
    "Why did the math book look sad? Because it had too many problems.",
    "I used to be a baker because I kneaded dough.",
    "Why don't scientists trust atoms? Because they make up everything!",
    "I'm not lazy; I'm in energy-saving mode.",
    "Why did the bicycle fall over? Because it was two-tired!"
};
